{
 "title": "Stock Market",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Apple stock price",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "producer_last_price{isin=\"US0378331005\"}",
     "legendFormat": "$"
    }
   ]
  },
  {
   "title": "Google stock price",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "producer_last_price{isin=\"US02079K1079\"}"
    }
   ]
  },
  {
   "title": "Prices",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "producer_last_price" }
   ]
  },
  {
   "title": "Stock prices",
   "type": "graph",
   "description": "Stock prices for Google and Apple",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "producer_last_price" }
   ]
  }
 ]
}